name: Point Cloud Evaluation Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check_commit_author:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check if last commit was by GitHub Actions
        id: check
        run: |
          LAST_COMMIT_AUTHOR=$(git log --format="%an" -n 1)
          if [[ "$LAST_COMMIT_AUTHOR" == "GitHub Actions" ]]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

  classification:
    needs: check_commit_author
    if: needs.check_commit_author.outputs.skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout datasets repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout ground truth repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.GROUND_TRUTH_REPO }}
          token: ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}
          path: ground-truth

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Run classification workflow
        run: |
          bash evaluation/run.sh
        env:
          GROUND_TRUTH_REPO_TOKEN: ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}

      - name: Run PR merged workflow
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          bash evaluation/pr_merged.sh
