name: Versioning

on:
  pull_request:
    types:
      - closed

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install bump2version
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Bump version
        id: bump_version
        run: |
          OLD_VERSION=$(cat VERSION)
          bump2version --commit --tag patch
          NEW_VERSION=$(cat VERSION)
          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit changes and tag
        run: |
          git commit -am "Bump version to $NEW_VERSION"
          git tag -a "v$NEW_VERSION" -m "Bump version to $NEW_VERSION"

      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push
          git push --tags
