name: Versioning and release

on:
  pull_request:
    types:
      - closed

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install bump2version
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        id: bump_version
        run: |
          OLD_VERSION=$(cat VERSION)
          bump2version --commit --tag patch
          NEW_VERSION=$(cat VERSION)
          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}
          tags: true

  release:
    needs: versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout ground truth repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.GROUND_TRUTH_REPO }}
          token: ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}
          path: ground-truth

      - name: Download new model and stats files
        run: |
          chmod +x evaluation/download_artifact.sh
          ./evaluation/download_artifact.sh ${{ github.repository }} evaluation.yml model ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}
          ./evaluation/download_artifact.sh ${{ github.repository }} evaluation.yml new-stats ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: Unzip stats archive and replace old stats file
        run: |
          unzip new-stats.zip
          find ground-truth -type f -iname "new-stats.json" -exec bash -c 'mv $0 ${0/new-/}' {} \;

      - name: Replace and push new stats files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cd ground-truth
          git add .
          git commit -m "Replace stats.json with new-stats.json"
          git push origin main

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Description of the release
          draft: false
          prerelease: false

      - name: Upload file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: new-model.bin
          asset_name: new-model.bin
          asset_content_type: text/plain